---
- name: Configure SELinux SSH port labeling.
  community.general.seport:
    ports: "{{ security_ssh_port }}"
    proto: tcp
    setype: ssh_port_t
    state: present
  when:
    - security_ssh_port | int != 22

- name: Ensure custom SSH port is allowed in firewalld.
  ansible.posix.firewalld:
    port: "{{ security_ssh_port }}/tcp"
    permanent: true
    immediate: true
    state: enabled
  when:
    - security_ssh_port | int != 22

- name: Remove default SSH service from firewalld when using a custom port.
  ansible.posix.firewalld:
    service: ssh
    permanent: true
    immediate: true
    state: disabled
  when:
    - security_ssh_port | int != 22
